### ISSUE TITLE
AttributeError: 'Trip' object has no attribute 'has_data'

### ISSUE THREAD

**Issue by martin131** [simontb/mojio-home-assistant#17]
Hi, I updated the component from the very old version and now Mojio is failing to start.

```Error setting up platform legacy mojio
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/device_tracker/legacy.py", line 292, in async_setup_legacy
    setup = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/mojio/device_tracker.py", line 42, in setup_scanner
    if not scanner.login(hass):
  File "/config/custom_components/mojio/device_tracker.py", line 77, in login
    self.setup(hass)
  File "/config/custom_components/mojio/device_tracker.py", line 68, in setup
    self._refresh()
  File "/config/custom_components/mojio/device_tracker.py", line 89, in _refresh
    if not last_comp_trip.has_data:
AttributeError: 'Trip' object has no attribute 'has_data'
```
config:
  - platform: mojio
    domain: tmobile-cz
    client_id: 01e950e3-5e50-4cc0-8b04-8b48c35d00cd
    client_secret: a1b7d477-9410-4e1d-b537-304e041fcb89
    username: user@gmail.com
    password: !secret mojio_pass

HA version: 2023.1.7

**Comment by themoosman** [comment]
Can you try adding `scan_interval: 5` to your config file?

**Comment by GSzabados** [comment]
Once I updated to the latest, added scan_interval and set the SDK version to the latest as well (PR added for that), the issue was solved for me.

So once the PR is merged, update your version and all should be fine!

**Comment by whit-tj** [comment]
> Once I updated to the latest, added scan_interval and set the SDK version to the latest as well (PR added for that), the issue was solved for me.
> 
> So once the PR is merged, update your version and all should be fine!

Just wanted to add that I finally got this working by doing these same changes in the US. Thank you so much!

**Comment by martin131** [comment]
> Once I updated to the latest, added scan_interval and set the SDK version to the latest as well (PR added for that), the issue was solved for me.
> 
> So once the PR is merged, update your version and all should be fine!

Works for me on the latest release with changed SDK version to 0.6.0. Thank you!

**Comment by GSzabados** [comment]
A bit late and off topic, but I want to ping @martin131 and @themoosman, does your dongles still report and can you access the location with the integration? It seems that T-Mobile Polska just discontinued the whole thing without any notice...

**Comment by themoosman** [comment]
I don't have the device any longer.

**Comment by GSzabados** [comment]
@themoosman, any chance that you are using something else? Or you changed cars which has tracking included in its API?

**Comment by themoosman** [comment]
I switched to Bouncie, which integrates with Home Assistant.  https://github.com/mandarons/ha-bouncie
