### ISSUE TITLE
Platform error device_tracker.mojio - Integration 'mojio' not found.

### ISSUE THREAD

**Issue by rainyvalley** [simontb/mojio-home-assistant#5]
Hello,

I recently installed the custom_component via HACS (I did verify that the custom component files are on the server and setup as an integration) . But, unfortunately, after restart and then adding in the configuration.yaml for the syncup drive (T-Mobile US found in the Pull Request) home assistant throws the following error: 
Platform error device_tracker.mojio - Integration 'mojio' not found.

Configuration:
  - platform: mojio
    domain: tmobile-us
    client_id: 86d1d812-dc08-4d38-9ff3-ff86908d97e6
    client_secret: 0a6b21ec-84df-4088-ba0c-2e05592da42b
    username: !secret syncupuser
    password: !secret syncuppass

Instance Details:
Version | core-2022.3.3
Installation Type | Home Assistant OS
Development | false
Supervisor | true
Docker | true
User | root
Virtual Environment | false
Python Version | 3.9.9
Operating System Family | Linux
Operating System Version | 5.10.98
CPU Architecture | x86_64
Timezone | America/Los_Angeles

Any assistance would be greatly appreciated!

**Comment by simontb** [comment]
This is most likely due to this missing version number of the mojio custom component. This is fixed now. Please update the mojio component and let me know if this solved your issue. For details have a look at #4

**Comment by rainyvalley** [comment]
Thank You- that did fix the issue!
