### ISSUE TITLE
A manual for dummies?

### ISSUE THREAD

**Issue by Bojkas1985** [simontb/mojio-home-assistant#9]
Hi, I tried to copy the integration via HACS, it copied the files and folders to custom_components, then I entered the parameters from the example configuration.yaml with the Czech operator, where I only changed the login and password (I left the api), but the vehicle did not appear. Only the update.moj.io sensor which is turned off.
What am I doing wrong? Is the API the same for everyone, or do I have to find it somewhere for my account?

**Comment by GSzabados** [comment]
Hi @Bojkas1985,

Could you paste here your relevant part of the configuration.yaml with redacted email and password? 

So do you have a Czech dongle?

Best Regards,

Gábor

**Comment by GSzabados** [comment]
Here is the example how it should be fulfilled:

https://github.com/simontb/mojio-home-assistant/pull/3/commits/1f6650f516a7e1b52d5f352a35f6db8447a57a60

**Comment by Bojkas1985** [comment]
Hi Gábor,

yes, i use czech tmobile dongle. I tried entering login and password with and without quotes. I literally copied what was in the config example.
Thank you for help
![image](https://user-images.githubusercontent.com/41238303/182391749-eb172b16-e308-470b-9441-612153b4dcf8.png)
![image](https://user-images.githubusercontent.com/41238303/182391864-3da8e7c8-e9eb-41b3-87d0-7dceac950b5f.png)
![image](https://user-images.githubusercontent.com/41238303/182391875-d81cf655-2b3e-4c97-b81c-7c53d55e12e1.png)

**Comment by GSzabados** [comment]
Search for `device_tracker`._your_plate_number_set_in_the_app_

**Comment by Bojkas1985** [comment]
it found nothing.  Not even another device tracker that looks like a car, just mobile phones and headphones.  I even have the impression that I don't have the option to enter the license plate number in my T-Mobile application.

**Comment by GSzabados** [comment]
To add the plate number in the tracker app, press the arrow on the top right, that should bring up the vehicles list. Click on the pencil icon on the right to edit the vehicle and in this menu you should have a license plate field below the VIN. Set your license plate there.

Otherwise check your log for any error messages with mojio in it.

**Comment by Bojkas1985** [comment]
thank you Gábor, that helped, so a license plate is required.  What does it actually do besides display GPS and home/not_home status?  :-) although this is also additional, but I didn't find any other sensors, I only see GPS in the attributes of the car.

**Comment by GSzabados** [comment]
There are a few PRs open by @themoosman both for the component and the python package it is using. Once it is merged it will have more attributes. 

https://github.com/simontb/mojio-home-assistant/pull/8

By the way, @simontb and @themoosman, as a follow up on this issue, can you add a check on the license plate, so if it is null then the integration would use the vehicle's name defined, if not null either?

**Comment by themoosman** [comment]
I could easily update the code to use VIN or mojio GUID as a fallback if the plate number is null or empty.

**Comment by simontb** [comment]
Hi @Bojkas1985,

the PR from @themoosman is now merged. Try to use version `0.6` of the mojio integration and let us know if this solved your issue.

**Comment by Bojkas1985** [comment]
Hi Guys,
after updating to the new version via HACS, the GPS display also stopped working.
![image](https://user-images.githubusercontent.com/41238303/182550027-d49f962c-a842-4ba4-89c6-dc0e90e4ea34.png)
![image](https://user-images.githubusercontent.com/41238303/182550149-96acf1f2-66ba-42d0-abea-a3d01a56ed69.png)
![image](https://user-images.githubusercontent.com/41238303/182550384-be15bf5d-ad23-459c-8b91-a57ab36f6616.png)

**Comment by themoosman** [comment]
That error leads me to believe that HA didn't pull down the mojio_sdk lib.  If you do an `ls` on `/config/custom_components/mojio/mojio_sdk/` I'll bet the directory is empty.

**Comment by Bojkas1985** [comment]
@themoosman yes, i don't have mojio_sdk folder, hacs doesn't download it. Can you please update hacs?

**Comment by Bojkas1985** [comment]
@themoosman so, now i will see sdk after the update from hacs or we waiting for PR? :)

**Comment by simontb** [comment]
PR is merged. Try version 0.6.1

**Comment by Bojkas1985** [comment]
@themoosman @simontb @GSzabados 
WOW! Guys, thank you so much, this is wonderful!! How often is the information updated if the car is on the way? And are you planning any more amazing features for the future?
![image](https://user-images.githubusercontent.com/41238303/182615797-61890972-f6e1-4e67-b757-c1832da53a29.png)

**Comment by GSzabados** [comment]
@themoosman, I've just updated as well. It looks awesome!

One more thing what would be good, if the refresh rate could be adjusted. As default it refreshes every 5 minutes, so I have changed the code immediately to update every minute. But a setting through the yaml config would be good.

**Comment by themoosman** [comment]
@GSzabados While testing, I set it to every 60 seconds as well.  I think the fear would be if it's left open, someone will inevitability set it to 1 second.

**Comment by GSzabados** [comment]
@themoosman, I thought of having a setting in minutes through the configuration.yaml otherwise if not set then it would use the default 5 minutes.

**Comment by simontb** [comment]
Yes, we discussed that @GSzabados.

I created follow up issues for the refresh interval: #13 and #14.

Closing this issue now. Thanks everyone.
